# Generated by Django 5.1.2 on 2024-10-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_requestlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlogs',
            name='request_method',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
